### ISSUE TITLE
NPE : Attempt to invoke virtual method 'void android.support.v4.app.FragmentManager.popBackStack()' on a null object reference

### ISSUE THREAD

**Issue by veiz** [baoyongzhang/android-ActionSheet#25]
Application crashed if using support library. Try to use getSupportedFragmentManager instead.

```java
public void dismiss() {
    if (mDismissed) {
        return;
    }
    mDismissed = true;
    new Handler().post(new Runnable() {
        public void run() {
            getFragmentManager().popBackStack();
            FragmentTransaction ft = getFragmentManager().beginTransaction();
            ft.remove(ActionSheet.this);
            ft.commitAllowingStateLoss();
        }
    });
}
```

**Comment by baoyongzhang** [comment]
Please provide exception stack trace.

**Comment by veiz** [comment]
```
java.lang.NullPointerException
	at com.baoyz.actionsheet.ActionSheet$2.run(ActionSheet.java:107)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5143)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by monkeyfdude** [comment]
Any updates on this issue? I observe the same issue.

**Comment by asrcraft** [comment]
I also find this problem,can you fix it?Thanks

**Comment by asrcraft** [comment]
I use it in "public void onBackPressed()", maybe something is released after calling this method, so get a NullPointerException, maybe there is some bug in your projrct?

**Comment by asrcraft** [comment]
I solved it, make "onBackPressed" running on another thread is ok!

**Comment by laconichy** [comment]
I also had the problem. setCancelableOnTouchOutside (true), this problem must occur when I always click on the event. This problem sometimes occurs when setCancelableOnTouchOutside (false).
@veiz What is your solution ? help me .

**Comment by laconichy** [comment]
My solution is to prevent duplicate clicks
